// Generated by LiveScript 1.3.1
(function(){
  var Button, cumulator, addClickingToFetchNumbersToAllButtons, addClickingToCalculateResultToTheBubble, addResettingWhenLeaveApb, reset, s1WaitUserClicking, robot, s2RobotClickButtonsFromAToEThenClickBubble, s4RobotGenerateARandomOrderAndThenClick;
  Button = (function(){
    Button.displayName = 'Button';
    var prototype = Button.prototype, constructor = Button;
    Button.FAILURERATE = 0.3;
    Button.buttons = [];
    Button.disableAllOtherButtons = function(thisButton){
      var i$, ref$, len$, button, results$ = [];
      for (i$ = 0, len$ = (ref$ = this.buttons).length; i$ < len$; ++i$) {
        button = ref$[i$];
        if (button !== thisButton && button.state !== 'done') {
          results$.push(button.disable());
        }
      }
      return results$;
    };
    Button.enableAllOtherButtons = function(thisButton){
      var i$, ref$, len$, button, results$ = [];
      for (i$ = 0, len$ = (ref$ = this.buttons).length; i$ < len$; ++i$) {
        button = ref$[i$];
        if (button !== thisButton && button.state !== 'done') {
          results$.push(button.enable());
        }
      }
      return results$;
    };
    Button.allButtonIsDone = function(){
      var i$, ref$, len$, button;
      for (i$ = 0, len$ = (ref$ = this.buttons).length; i$ < len$; ++i$) {
        button = ref$[i$];
        if (button.state !== 'done') {
          return false;
        }
      }
      return true;
    };
    Button.resetAll = function(){
      var i$, ref$, len$, button;
      for (i$ = 0, len$ = (ref$ = this.buttons).length; i$ < len$; ++i$) {
        button = ref$[i$];
        button.reset();
      }
    };
    function Button(dom, goodMessage, badMessage, numberFetchedCallback){
      var this$ = this;
      this.dom = dom;
      this.goodMessage = goodMessage;
      this.badMessage = badMessage;
      this.numberFetchedCallback = numberFetchedCallback;
      this.state = 'enabled';
      this.dom.addClass('enabled');
      this.name = this.dom.find('.title').text();
      this.dom.click(function(){
        if (this$.state === 'enabled') {
          this$.constructor.disableAllOtherButtons(this$);
          this$.wait();
          this$.fetchNumberAndShow();
        }
      });
      this.constructor.buttons.push(this);
    }
    prototype.fetchNumberAndShow = function(){
      var this$ = this;
      $.get('/api/random', function(number, result){
        this$.done();
        if (this$.constructor.allButtonIsDone()) {
          this$.constructor.allNumberFetchedCallback();
        }
        this$.constructor.enableAllOtherButtons(this$);
        this$.showNumber(number);
        this$.successOrFail(number);
      });
    };
    prototype.showNumber = function(number){
      this.dom.find('.unread').text(number);
    };
    prototype.successOrFail = function(number){
      var isSuccess, error;
      if (isSuccess = Math.random() > this.constructor.FAILURERATE) {
        this.showMessage(this.goodMessage);
        this.numberFetchedCallback(error = null, number);
      } else {
        this.numberFetchedCallback({
          message: this.badMessage,
          data: number
        });
      }
    };
    prototype.showMessage = function(){
      console.log("Button " + this.name + " say: " + this.goodMessage);
    };
    prototype.disable = function(){
      this.state = 'disabled';
      this.dom.removeClass('enabled').addClass('disabled');
    };
    prototype.enable = function(){
      this.state = 'enabled';
      this.dom.removeClass('disabled').addClass('enabled');
    };
    prototype.wait = function(){
      this.state = 'waiting';
      this.dom.removeClass('enabled').addClass('waiting');
    };
    prototype.done = function(){
      this.state = 'done';
      this.dom.removeClass('waiting').addClass('done');
    };
    prototype.reset = function(){
      this.state = 'enabled';
      this.dom.removeClass('disabled waiting done').addClass('enabled');
      this.dom.find('.unread').text('');
    };
    return Button;
  }());
  cumulator = {
    sum: 0,
    add: function(number){
      return this.sum += parseInt(number);
    },
    reset: function(){
      this.sum = 0;
    }
  };
  $(function(){
    robot.initial();
    addClickingToFetchNumbersToAllButtons(function(){
      robot.clickNext();
    });
    addClickingToCalculateResultToTheBubble();
    addResettingWhenLeaveApb();
    s1WaitUserClicking();
    return s4RobotGenerateARandomOrderAndThenClick();
  });
  addClickingToFetchNumbersToAllButtons = function(next){
    var goodMessages, badMessages, i$, ref$, len$, results$ = [];
    goodMessages = ['这是个天大的秘密', '我不知道', '你不知道', '他不知道', '才怪'];
    badMessages = ['这不是个天大的秘密', '我知道', '你知道', '他知道', '才怪'];
    for (i$ = 0, len$ = (ref$ = $('#control-ring .button')).length; i$ < len$; ++i$) {
      results$.push((fn$.call(this, i$, ref$[i$])));
    }
    return results$;
    function fn$(i, dom){
      var button;
      return button = new Button($(dom), goodMessages[i], badMessages[i], function(error, number){
        if (error) {
          console.log("Handle error from " + button.name + ", message is: " + error.message);
          number = error.data;
        }
        cumulator.add(number);
        if (typeof next == 'function') {
          next();
        }
      });
    }
  };
  addClickingToCalculateResultToTheBubble = function(){
    var bubble;
    bubble = $('#info-bar');
    bubble.addClass('disabled');
    Button.allNumberFetchedCallback = function(){
      bubble.removeClass('disabled').addClass('enabled');
    };
    return bubble.click(function(){
      if (bubble.hasClass('enabled')) {
        bubble.find('.amount').text(cumulator.sum);
      }
    });
  };
  addResettingWhenLeaveApb = function(){
    var isEnterOther;
    isEnterOther = false;
    $('#info-bar, #control-ring').on('mouseenter', function(){
      isEnterOther = true;
    });
    $('#info-bar, #control-ring').on('mouseleave', function(event){
      isEnterOther = false;
      setTimeout(function(){
        if (!isEnterOther) {
          reset();
        }
      }, 0);
    });
  };
  reset = function(){
    var bubble;
    cumulator.reset();
    Button.resetAll();
    bubble = $('#info-bar');
    bubble.removeClass('enabled').addClass('disabled');
    bubble.find('.amount span').text('');
  };
  s1WaitUserClicking = function(){
    console.log("wait user clicking ...");
  };
  robot = {
    initial: function(){
      this.buttons = $('#control-ring .button');
      this.bubble = $('#info-bar');
      this.sequence = ["A", "B", "C", "D", "E"];
      this.cursor = 0;
    },
    shuffleOrder: function(){
      this.sequence.sort(function(){
        return 0.5 - Math.random();
      });
    },
    clickNext: function(){
      if (this.cursor === this.sequence.length) {
        this.bubble.click();
      } else {
        this.getNextButton().click();
      }
    },
    getNextButton: function(){
      var index;
      index = this.sequence[this.cursor++].charCodeAt() - 'A'.charCodeAt();
      return this.buttons[index];
    },
    showOrder: function(){
      this.bubble.find('.sequence span').text(this.sequence.join(', '));
    }
  };
  s2RobotClickButtonsFromAToEThenClickBubble = function(){
    $('#button .apb').click(function(){
      robot.clickNext();
    });
  };
  s4RobotGenerateARandomOrderAndThenClick = function(){
    $('#button .apb').click(function(){
      robot.shuffleOrder();
      robot.showOrder();
      robot.clickNext();
    });
  };
}).call(this);
